language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc
env:
  - QUICKCHECK_TESTS=10000 QUICKCHECK_MAX_TESTS=1000000
matrix:
  fast_finish: true
